export const paysListe = [
    { value:"AFG", land:"Afghane (Afghanistan)"},
    { value:"ALB", land:"Albanaise (Albanie)"},
    { value:"DZA", land:"Algérienne (Algérie)"},
    { value:"DEU", land:"Allemande (Allemagne)"},
    { value:"USA", land:"Americaine (États-Unis)"},
    { value:"AND", land:"Andorrane (Andorre)"},
    { value:"AGO", land:"Angolaise (Angola)"},
    { value:"ATG", land:"Antiguaise-et-Barbudienne (Antigua-et-Barbuda)"},
    { value:"ARG", land:"Argentine (Argentine)"},
    { value:"ARM", land:"Armenienne (Arménie)"},
    { value:"AUS", land:"Australienne (Australie)"},
    { value:"AUT", land:"Autrichienne (Autriche)"},
    { value:"AZE", land:"Azerbaïdjanaise (Azerbaïdjan)"},
    { value:"BHS", land:"Bahamienne (Bahamas)"},
    { value:"BHR", land:"Bahreinienne (Bahreïn)"},
    { value:"BGD", land:"Bangladaise (Bangladesh)"},
    { value:"BRB", land:"Barbadienne (Barbade)"},
    { value:"BEL", land:"Belge (Belgique)"},
    { value:"BLZ", land:"Belizienne (Belize)"},
    { value:"BEN", land:"Béninoise (Bénin)"},
    { value:"BTN", land:"Bhoutanaise (Bhoutan)"},
    { value:"BLR", land:"Biélorusse (Biélorussie)"},
    { value:"MMR", land:"Birmane (Birmanie)"},
    { value:"GNB", land:"Bissau-Guinéenne (Guinée-Bissau)"},
    { value:"BOL", land:"Bolivienne (Bolivie)"},
    { value:"BIH", land:"Bosnienne (Bosnie-Herzégovine)"},
    { value:"BWA", land:"Botswanaise (Botswana)"},
    { value:"BRA", land:"Brésilienne (Brésil)"},
    { value:"GBR", land:"Britannique (Royaume-Uni)"},
    { value:"BRN", land:"Brunéienne (Brunéi)"},
    { value:"BGR", land:"Bulgare (Bulgarie)"},
    { value:"BFA", land:"Burkinabée (Burkina)"},
    { value:"BDI", land:"Burundaise (Burundi)"},
    { value:"KHM", land:"Cambodgienne (Cambodge)"},
    { value:"CMR", land:"Camerounaise (Cameroun)"},
    { value:"CAN", land:"Canadienne (Canada)"},
    { value:"CPV", land:"Cap-verdienne (Cap-Vert)"},
    { value:"CAF", land:"Centrafricaine (Centrafrique)"},
    { value:"CHL", land:"Chilienne (Chili)"},
    { value:"CHN", land:"Chinoise (Chine)"},
    { value:"CYP", land:"Chypriote (Chypre)"},
    { value:"COL", land:"Colombienne (Colombie)"},
    { value:"COM", land:"Comorienne (Comores)"},
    { value:"COG", land:"Congolaise (Congo-Brazzaville)"},
    { value:"COD", land:"Congolaise (Congo-Kinshasa)"},
    { value:"COK", land:"Cookienne (Îles Cook)"},
    { value:"CRI", land:"Costaricaine (Costa Rica)"},
    { value:"HRV", land:"Croate (Croatie)"},
    { value:"CUB", land:"Cubaine (Cuba)"},
    { value:"DNK", land:"Danoise (Danemark)"},
    { value:"DJI", land:"Djiboutienne (Djibouti)"},
    { value:"DOM", land:"Dominicaine (République dominicaine)"},
    { value:"DMA", land:"Dominiquaise (Dominique)"},
    { value:"EGY", land:"Égyptienne (Égypte)"},
    { value:"ARE", land:"Émirienne (Émirats arabes unis)"},
    { value:"GNQ", land:"Équato-guineenne (Guinée équatoriale)"},
    { value:"ECU", land:"Équatorienne (Équateur)"},
    { value:"ERI", land:"Érythréenne (Érythrée)"},
    { value:"ESP", land:"Espagnole (Espagne)"},
    { value:"TLS", land:"Est-timoraise (Timor-Leste)"},
    { value:"EST", land:"Estonienne (Estonie)"},
    { value:"ETH", land:"Éthiopienne (Éthiopie)"},
    { value:"FJI", land:"Fidjienne (Fidji)"},
    { value:"FIN", land:"Finlandaise (Finlande)"},
    { value:"FRA", land:"Française (France)"},
    { value:"GAB", land:"Gabonaise (Gabon)"},
    { value:"GMB", land:"Gambienne (Gambie)"},
    { value:"GEO", land:"Georgienne (Géorgie)"},
    { value:"GHA", land:"Ghanéenne (Ghana)"},
    { value:"GRD", land:"Grenadienne (Grenade)"},
    { value:"GTM", land:"Guatémaltèque (Guatemala)"},
    { value:"GIN", land:"Guinéenne (Guinée)"},
    { value:"GUY", land:"Guyanienne (Guyana)"},
    { value:"HTI", land:"Haïtienne (Haïti)"},
    { value:"GRC", land:"Hellénique (Grèce)"},
    { value:"HND", land:"Hondurienne (Honduras)"},
    { value:"HUN", land:"Hongroise (Hongrie)"},
    { value:"IND", land:"Indienne (Inde)"},
    { value:"IDN", land:"Indonésienne (Indonésie)"},
    { value:"IRQ", land:"Irakienne (Iraq)"},
    { value:"IRN", land:"Iranienne (Iran)"},
    { value:"IRL", land:"Irlandaise (Irlande)"},
    { value:"ISL", land:"Islandaise (Islande)"},
    { value:"ISR", land:"Israélienne (Israël)"},
    { value:"ITA", land:"Italienne (Italie)"},
    { value:"CIV", land:"Ivoirienne (Côte d'Ivoire)"},
    { value:"JAM", land:"Jamaïcaine (Jamaïque)"},
    { value:"JPN", land:"Japonaise (Japon)"},
    { value:"JOR", land:"Jordanienne (Jordanie)"},
    { value:"KAZ", land:"Kazakhstanaise (Kazakhstan)"},
    { value:"KEN", land:"Kenyane (Kenya)"},
    { value:"KGZ", land:"Kirghize (Kirghizistan)"},
    { value:"KIR", land:"Kiribatienne (Kiribati)"},
    { value:"KNA", land:"Kittitienne et Névicienne (Saint-Christophe-et-Niévès)"},
    { value:"KWT", land:"Koweïtienne (Koweït)"},
    { value:"LAO", land:"Laotienne (Laos)"},
    { value:"LSO", land:"Lesothane (Lesotho)"},
    { value:"LVA", land:"Lettone (Lettonie)"},
    { value:"LBN", land:"Libanaise (Liban)"},
    { value:"LBR", land:"Libérienne (Libéria)"},
    { value:"LBY", land:"Libyenne (Libye)"},
    { value:"LIE", land:"Liechtensteinoise (Liechtenstein)"},
    { value:"LTU", land:"Lituanienne (Lituanie)"},
    { value:"LUX", land:"Luxembourgeoise (Luxembourg)"},
    { value:"MKD", land:"Macédonienne (Macédoine)"},
    { value:"MYS", land:"Malaisienne (Malaisie)"},
    { value:"MWI", land:"Malawienne (Malawi)"},
    { value:"MDV", land:"Maldivienne (Maldives)"},
    { value:"MDG", land:"Malgache (Madagascar)"},
    { value:"MLI", land:"Maliennes (Mali)"},
    { value:"MLT", land:"Maltaise (Malte)"},
    { value:"MAR", land:"Marocaine (Maroc)"},
    { value:"MHL", land:"Marshallaise (Îles Marshall)"},
    { value:"MUS", land:"Mauricienne (Maurice)"},
    { value:"MRT", land:"Mauritanienne (Mauritanie)"},
    { value:"MEX", land:"Mexicaine (Mexique)"},
    { value:"FSM", land:"Micronésienne (Micronésie)"},
    { value:"MDA", land:"Moldave (Moldovie)"},
    { value:"MCO", land:"Monegasque (Monaco)"},
    { value:"MNG", land:"Mongole (Mongolie)"},
    { value:"MNE", land:"Monténégrine (Monténégro)"},
    { value:"MOZ", land:"Mozambicaine (Mozambique)"},
    { value:"NAM", land:"Namibienne (Namibie)"},
    { value:"NRU", land:"Nauruane (Nauru)"},
    { value:"NLD", land:"Néerlandaise (Pays-Bas)"},
    { value:"NZL", land:"Néo-Zélandaise (Nouvelle-Zélande)"},
    { value:"NPL", land:"Népalaise (Népal)"},
    { value:"NIC", land:"Nicaraguayenne (Nicaragua)"},
    { value:"NGA", land:"Nigériane (Nigéria)"},
    { value:"NER", land:"Nigérienne (Niger)"},
    { value:"NIU", land:"Niuéenne (Niue)"},
    { value:"PRK", land:"Nord-coréenne (Corée du Nord)"},
    { value:"NOR", land:"Norvégienne (Norvège)"},
    { value:"OMN", land:"Omanaise (Oman)"},
    { value:"UGA", land:"Ougandaise (Ouganda)"},
    { value:"UZB", land:"Ouzbéke (Ouzbékistan)"},
    { value:"PAK", land:"Pakistanaise (Pakistan)"},
    { value:"PLW", land:"Palaosienne (Palaos)"},
    { value:"PSE", land:"Palestinienne (Palestine)"},
    { value:"PAN", land:"Panaméenne (Panama)"},
    { value:"PNG", land:"Papouane-Néo-Guinéenne (Papouasie-Nouvelle-Guinée)"},
    { value:"PRY", land:"Paraguayenne (Paraguay)"},
    { value:"PER", land:"Péruvienne (Pérou)"},
    { value:"PHL", land:"Philippine (Philippines)"},
    { value:"POL", land:"Polonaise (Pologne)"},
    { value:"PRT", land:"Portugaise (Portugal)"},
    { value:"QAT", land:"Qatarienne (Qatar)"},
    { value:"ROU", land:"Roumaine (Roumanie)"},
    { value:"RUS", land:"Russe (Russie)"},
    { value:"RWA", land:"Rwandaise (Rwanda)"},
    { value:"LCA", land:"Saint-Lucienne (Sainte-Lucie)"},
    { value:"SMR", land:"Saint-Marinaise (Saint-Marin)"},
    { value:"VCT", land:"Saint-Vincentaise et Grenadine (Saint-Vincent-et-les Grenadines)"},
    { value:"SLB", land:"Salomonaise (Îles Salomon)"},
    { value:"SLV", land:"Salvadorienne (Salvador)"},
    { value:"WSM", land:"Samoane (Samoa)"},
    { value:"STP", land:"Santoméenne (Sao Tomé-et-Principe)"},
    { value:"SAU", land:"Saoudienne (Arabie saoudite)"},
    { value:"SEN", land:"Sénégalaise (Sénégal)"},
    { value:"SRB", land:"Serbe (Serbie)"},
    { value:"SYC", land:"Seychelloise (Seychelles)"},
    { value:"SLE", land:"Sierra-Léonaise (Sierra Leone)"},
    { value:"SGP", land:"Singapourienne (Singapour)"},
    { value:"SVK", land:"Slovaque (Slovaquie)"},
    { value:"SVN", land:"Slovène (Slovénie)"},
    { value:"SOM", land:"Somalienne (Somalie)"},
    { value:"SDN", land:"Soudanaise (Soudan)"},
    { value:"LKA", land:"Sri-Lankaise (Sri Lanka)"},
    { value:"ZAF", land:"Sud-Africaine (Afrique du Sud)"},
    { value:"KOR", land:"Sud-Coréenne (Corée du Sud)"},
    { value:"SSD", land:"Sud-Soudanaise (Soudan du Sud)"},
    { value:"SWE", land:"Suédoise (Suède)"},
    { value:"CHE", land:"Suisse (Suisse)"},
    { value:"SUR", land:"Surinamaise (Suriname)"},
    { value:"SWZ", land:"Swazie (Swaziland)"},
    { value:"SYR", land:"Syrienne (Syrie)"},
    { value:"TJK", land:"Tadjike (Tadjikistan)"},
    { value:"TZA", land:"Tanzanienne (Tanzanie)"},
    { value:"TCD", land:"Tchadienne (Tchad)"},
    { value:"CZE", land:"Tchèque (Tchéquie)"},
    { value:"THA", land:"Thaïlandaise (Thaïlande)"},
    { value:"TGO", land:"Togolaise (Togo)"},
    { value:"TON", land:"Tonguienne (Tonga)"},
    { value:"TTO", land:"Trinidadienne (Trinité-et-Tobago)"},
    { value:"TUN", land:"Tunisienne (Tunisie)"},
    { value:"TKM", land:"Turkmène (Turkménistan)"},
    { value:"TUR", land:"Turque (Turquie)"},
    { value:"TUV", land:"Tuvaluane (Tuvalu)"},
    { value:"UKR", land:"Ukrainienne (Ukraine)"},
    { value:"URY", land:"Uruguayenne (Uruguay)"},
    { value:"VUT", land:"Vanuatuane (Vanuatu)"},
    { value:"VAT", land:"Vaticane (Vatican)"},
    { value:"VEN", land:"Vénézuélienne (Venezuela)"},
    { value:"VNM", land:"Vietnamienne (Viêt Nam)"},
    { value:"YEM", land:"Yéménite (Yémen)"},
    { value:"ZMB", land:"Zambienne (Zambie)"},
    { value:"ZWE", land:"Zimbabwéenne (Zimbabwe)"}
];